language: python
sudo: required
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r ./GUIs/ScriptRunnerPyQt5_GUI/requirements.txt
before-script:
  - chmod +x ./builds/tests/compile_test.sh
# command to run tests
script:
  - pytest ./builds/tests/compile_test.py
