language: python
sudo: required
jobs:
  include:
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      language: generic
      env: TOXENV=py38
python:
  - "3.8"
# command to install dependencies
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip3 install -r ./GUIs/ScriptRunnerPyQt5_GUI/requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install -r ./GUIs/ScriptRunnerPyQt5_GUI/requirements.txt; fi
before-script:
  - chmod +x ./builds/tests/compile_test.sh
# command to run tests
script:
  - ./builds/tests/compile_test.sh
