= CP_Scripts2
Michael Brenner
:toc:

Website: https://matrix0501.com

image:https://app.codacy.com/project/badge/Grade/d277e9b251a74fc0a61da1fc321a9bfa["Codacy code quality",link="https://www.codacy.com/manual/vipersniper0501/CP_Scripts2?utm_source=github.com&utm_medium=referral&utm_content=vipersniper0501/CP_Scripts2&utm_campaign=Badge_Grade"]
image:https://img.shields.io/github/issues-raw/vipersniper0501/CP_Scripts2[GitHub issues]
image:https://img.shields.io/github/repo-size/vipersniper0501/CP_Scripts2[GitHub repo size]
image:https://github.com/vipersniper0501/CP_Scripts2/workflows/Compilation/badge.svg?branch=dev[link="https://github.com/vipersniper0501/CP_Scripts2/actions?query=workflow%3ACompilation"]

NOTE: This is program is Pre-Alpha so it still has many bugs and is missing many of the core features.
I am only one person so this will take a while to even get to Alpha.
Thank you for your understanding.

Before using any of these scripts for the CyberPatriot challenges, please make sure
that you complete as many of the Forensic Questions as possible! If not, then you risk the chance
that the script will remove or change something that the Forensics Question requires later.

'''

== Description

This script was made for myself and team mates for the AFA Cyberpatriots Competition. This program is compatible with Debian/Ubuntu based linux distrobutions and windows 10.
You can use this program to configure commonly used services and programs along with user and security auditing, along with firewall configuration.

== How to use

All you will have to do is download the executable from my website https://matrix0501.com/CyberSecurity/Apple_CIDR_Script_Runner.html[Matrix0501.com], from the Releases tab, or compile it yourself.
Once downloaded, run as administrator/sudo and you should be up and running. :)

NOTE: Please again note that this is a work in progress by a highschooler in his free time. I do my best to get as much of it working as I can, however there will bugs and I can't catch everything myself. If you find a bug please let me know by creating an Issue or even better, help me out and create a pull request ;). 

== How to compile

Make sure you have the correct version of Pyinstaller:

`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz`

Run `pip install auto-py-to-exe` to install the compiler.

NOTE: For executables that work on **Windows:** Run auto-py-to-exe on a windows machine. +
For executables that work with **Linux:** Run auto-py-to-exe on a Linux/Unix machine.

1.) Move all files that are to be converted into a .exe onto the desktop. +
2.) open powershell/terminal as admin and type `auto-py-to-exe` +
3.) In `Script Location` in the newly opened window, put in the location of the .py file that launches the GUI +
4.) Under Additional Files, add all folders and files that are to be used in the script +
5.) Under Advanced, change Output Directory to the desktop to easily locate the newly created .exe file +
6.) Hit `Convert .PY TO .EXE` +
7.) your newly created .exe file should now have been created and added to the desktop

https://dev.to/eshleron/how-to-convert-py-to-exe-step-by-step-guide-3cfi

== Version Numbers

1.2.3.4

**First Number:** Generation (General Information -> 0, Cli -> 1, Tkinter -> 2, PyQt5 ->3, Electron -> 4) +
This number is to be used to identify which generation of script has been changed.
For example, if I were to change something in the CLI version it would uploaded as version 1.x.x.x,
but if I were to change something in the Electron version, I would upload as version 4.x.x.x

**Second Number:** used for noting number of os's completely supported in the generation

**Third Number:** Number of completed commands regardless of OS type or section of program (mainly
used in the GUI versions).

*Fourth Number:* used for patches, minor updates, and updates that are working towards a new feature. +
This is also updated when code has been edited to become more efficient or after finding a typo and
making a quick edit. Also changes if a file was forgotten when pushing to the repository.

NOTE: When ever a version number has been updated, all of the numbers to the right of the changed
number is set to zero.

== FaQ
[qanda]
Why is it that when I download the exe, it says it is malware?::
    This is because I have not yet been able to sign my executables. So as of right now, windows
does not know that this program is safe so it try's to warn you that this is not an official
program.


