# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rmv_usr_o_gru.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(291, 334)
        Dialog.setStyleSheet("background-color: #212434\n"
                             "            ")
        self.Username_Input = QtWidgets.QLineEdit(Dialog)
        self.Username_Input.setGeometry(QtCore.QRect(140, 250, 141, 21))
        self.Username_Input.setStyleSheet("background-color: #414E6E;color: #CCD2E6;border: none;")
        self.Username_Input.setObjectName("Username_Input")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 271, 191))
        self.label.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(200, 290, 81, 31))
        self.pushButton.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 290, 81, 31))
        self.pushButton_2.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.Username_Label = QtWidgets.QLabel(Dialog)
        self.Username_Label.setGeometry(QtCore.QRect(10, 250, 121, 21))
        self.Username_Label.setStyleSheet("color: #8B93B2;")
        self.Username_Label.setText("")
        self.Username_Label.setObjectName("Username_Label")
        self.Username_Label_2 = QtWidgets.QLabel(Dialog)
        self.Username_Label_2.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.Username_Label_2.setStyleSheet("color: #8B93B2;")
        self.Username_Label_2.setText("")
        self.Username_Label_2.setObjectName("Username_Label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Cancel"))
        self.pushButton_2.setText(_translate("Dialog", "Confirm"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
