# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mmtab = QtWidgets.QTabWidget(self.centralwidget)
        self.mmtab.setGeometry(QtCore.QRect(0, 0, 611, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mmtab.setFont(font)
        self.mmtab.setIconSize(QtCore.QSize(12, 12))
        self.mmtab.setObjectName("mmtab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.fwlbutton = QtWidgets.QPushButton(self.tab)
        self.fwlbutton.setGeometry(QtCore.QRect(50, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwlbutton.setFont(font)
        self.fwlbutton.setObjectName("fwlbutton")
        self.auditbutton = QtWidgets.QPushButton(self.tab)
        self.auditbutton.setGeometry(QtCore.QRect(50, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auditbutton.setFont(font)
        self.auditbutton.setObjectName("auditbutton")
        self.servsetbutton = QtWidgets.QPushButton(self.tab)
        self.servsetbutton.setGeometry(QtCore.QRect(330, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.servsetbutton.setFont(font)
        self.servsetbutton.setObjectName("servsetbutton")
        self.rmvprosoftbutton = QtWidgets.QPushButton(self.tab)
        self.rmvprosoftbutton.setGeometry(QtCore.QRect(50, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvprosoftbutton.setFont(font)
        self.rmvprosoftbutton.setObjectName("rmvprosoftbutton")
        self.malrembutton = QtWidgets.QPushButton(self.tab)
        self.malrembutton.setGeometry(QtCore.QRect(330, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.malrembutton.setFont(font)
        self.malrembutton.setObjectName("malrembutton")
        self.srchmedbutton = QtWidgets.QPushButton(self.tab)
        self.srchmedbutton.setGeometry(QtCore.QRect(330, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.srchmedbutton.setFont(font)
        self.srchmedbutton.setObjectName("srchmedbutton")
        self.quit_button = QtWidgets.QPushButton(self.tab)
        self.quit_button.setGeometry(QtCore.QRect(500, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quit_button.setFont(font)
        self.quit_button.setObjectName("quit_button")
        self.mmlbl = QtWidgets.QLabel(self.tab)
        self.mmlbl.setGeometry(QtCore.QRect(10, 0, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(False)
        self.mmlbl.setFont(font)
        self.mmlbl.setObjectName("mmlbl")
        self.Updates_button = QtWidgets.QPushButton(self.tab)
        self.Updates_button.setGeometry(QtCore.QRect(50, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Updates_button.setFont(font)
        self.Updates_button.setAcceptDrops(False)
        self.Updates_button.setObjectName("Updates_button")
        self.basicConfbutton = QtWidgets.QPushButton(self.tab)
        self.basicConfbutton.setGeometry(QtCore.QRect(330, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.basicConfbutton.setFont(font)
        self.basicConfbutton.setObjectName("basicConfbutton")
        self.mmtab.addTab(self.tab, "")
        self.usrgrutab = QtWidgets.QWidget()
        self.usrgrutab.setObjectName("usrgrutab")
        self.usrgrulbl = QtWidgets.QLabel(self.usrgrutab)
        self.usrgrulbl.setGeometry(QtCore.QRect(10, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(False)
        self.usrgrulbl.setFont(font)
        self.usrgrulbl.setObjectName("usrgrulbl")
        self.lslocausr = QtWidgets.QPushButton(self.usrgrutab)
        self.lslocausr.setGeometry(QtCore.QRect(50, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocausr.setFont(font)
        self.lslocausr.setObjectName("lslocausr")
        self.rmvusrfrogru = QtWidgets.QPushButton(self.usrgrutab)
        self.rmvusrfrogru.setGeometry(QtCore.QRect(330, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrogru.setFont(font)
        self.rmvusrfrogru.setObjectName("rmvusrfrogru")
        self.adgrutosys = QtWidgets.QPushButton(self.usrgrutab)
        self.adgrutosys.setGeometry(QtCore.QRect(50, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adgrutosys.setFont(font)
        self.adgrutosys.setObjectName("adgrutosys")
        self.rmvgrufrosys = QtWidgets.QPushButton(self.usrgrutab)
        self.rmvgrufrosys.setGeometry(QtCore.QRect(330, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvgrufrosys.setFont(font)
        self.rmvgrufrosys.setObjectName("rmvgrufrosys")
        self.quit_button_3 = QtWidgets.QPushButton(self.usrgrutab)
        self.quit_button_3.setGeometry(QtCore.QRect(500, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quit_button_3.setFont(font)
        self.quit_button_3.setObjectName("quit_button_3")
        self.adusrtosys = QtWidgets.QPushButton(self.usrgrutab)
        self.adusrtosys.setGeometry(QtCore.QRect(50, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtosys.setFont(font)
        self.adusrtosys.setAcceptDrops(False)
        self.adusrtosys.setObjectName("adusrtosys")
        self.lslocagru = QtWidgets.QPushButton(self.usrgrutab)
        self.lslocagru.setGeometry(QtCore.QRect(330, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocagru.setFont(font)
        self.lslocagru.setObjectName("lslocagru")
        self.adusrtogru = QtWidgets.QPushButton(self.usrgrutab)
        self.adusrtogru.setGeometry(QtCore.QRect(50, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtogru.setFont(font)
        self.adusrtogru.setObjectName("adusrtogru")
        self.rmvusrfrosys = QtWidgets.QPushButton(self.usrgrutab)
        self.rmvusrfrosys.setGeometry(QtCore.QRect(330, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrosys.setFont(font)
        self.rmvusrfrosys.setObjectName("rmvusrfrosys")
        self.lsmemgru = QtWidgets.QPushButton(self.usrgrutab)
        self.lsmemgru.setGeometry(QtCore.QRect(50, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsmemgru.setFont(font)
        self.lsmemgru.setObjectName("lsmemgru")
        self.lsgruusrin = QtWidgets.QPushButton(self.usrgrutab)
        self.lsgruusrin.setGeometry(QtCore.QRect(330, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsgruusrin.setFont(font)
        self.lsgruusrin.setObjectName("lsgruusrin")
        self.chngusrpas = QtWidgets.QPushButton(self.usrgrutab)
        self.chngusrpas.setGeometry(QtCore.QRect(50, 250, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chngusrpas.setFont(font)
        self.chngusrpas.setObjectName("chngusrpas")
        self.mmtab.addTab(self.usrgrutab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_Creator = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionAbout_Creator.setFont(font)
        self.actionAbout_Creator.setObjectName("actionAbout_Creator")
        self.actionHow_To_Use = QtWidgets.QAction(MainWindow)
        self.actionHow_To_Use.setObjectName("actionHow_To_Use")
        self.menuAbout.addAction(self.actionAbout_Creator)
        self.menuAbout.addAction(self.actionHow_To_Use)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.mmtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Apple CIDR Script Runner"))
        self.fwlbutton.setText(_translate("MainWindow", "Firewall Settings"))
        self.auditbutton.setText(_translate("MainWindow", "Audit System"))
        self.servsetbutton.setText(_translate("MainWindow", "Services Settings"))
        self.rmvprosoftbutton.setText(_translate("MainWindow", "Remove Prohibited Software"))
        self.malrembutton.setText(_translate("MainWindow", "Malware Removal"))
        self.srchmedbutton.setText(_translate("MainWindow", "Search For Prohibited Media"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.quit_button.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.mmlbl.setText(_translate("MainWindow", "Main Menu"))
        self.Updates_button.setText(_translate("MainWindow", "Updates"))
        self.basicConfbutton.setText(_translate("MainWindow", "Basic Configurations"))
        self.mmtab.setTabText(self.mmtab.indexOf(self.tab), _translate("MainWindow", "Main Menu"))
        self.usrgrulbl.setText(_translate("MainWindow", "User / Group Settings"))
        self.lslocausr.setText(_translate("MainWindow", "List Local Users"))
        self.rmvusrfrogru.setText(_translate("MainWindow", "Remove User from Group"))
        self.adgrutosys.setText(_translate("MainWindow", "Add Group to System"))
        self.rmvgrufrosys.setText(_translate("MainWindow", "Remove Group from System"))
        self.quit_button_3.setText(_translate("MainWindow", "Quit"))
        self.quit_button_3.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.adusrtosys.setText(_translate("MainWindow", "Add User to System"))
        self.lslocagru.setText(_translate("MainWindow", "List Local Groups"))
        self.adusrtogru.setText(_translate("MainWindow", "Add User to Group"))
        self.rmvusrfrosys.setText(_translate("MainWindow", "Remove User From System"))
        self.lsmemgru.setText(_translate("MainWindow", "List Members of Group"))
        self.lsgruusrin.setText(_translate("MainWindow", "List Groups an User is in"))
        self.chngusrpas.setText(_translate("MainWindow", "Change all Users Passwords at Once"))
        self.mmtab.setTabText(self.mmtab.indexOf(self.usrgrutab), _translate("MainWindow", "User / Group Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_Creator.setText(_translate("MainWindow", "About Creator"))
        self.actionHow_To_Use.setText(_translate("MainWindow", "How To Use"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
