# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(850, 610)
        MainWindow.setStyleSheet("background-color: #212434\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmdCHNG = QtWidgets.QFrame(self.centralwidget)
        self.cmdCHNG.setGeometry(QtCore.QRect(0, 120, 291, 401))
        self.cmdCHNG.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cmdCHNG.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cmdCHNG.setObjectName("cmdCHNG")
        self.uniCom = QtWidgets.QPushButton(self.cmdCHNG)
        self.uniCom.setGeometry(QtCore.QRect(120, 10, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uniCom.setFont(font)
        self.uniCom.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.uniCom.setObjectName("uniCom")
        self.winCom = QtWidgets.QPushButton(self.cmdCHNG)
        self.winCom.setGeometry(QtCore.QRect(120, 110, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.winCom.setFont(font)
        self.winCom.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.winCom.setObjectName("winCom")
        self.linCom = QtWidgets.QPushButton(self.cmdCHNG)
        self.linCom.setGeometry(QtCore.QRect(120, 210, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linCom.setFont(font)
        self.linCom.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.linCom.setObjectName("linCom")
        self.macCom = QtWidgets.QPushButton(self.cmdCHNG)
        self.macCom.setGeometry(QtCore.QRect(120, 310, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.macCom.setFont(font)
        self.macCom.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.macCom.setObjectName("macCom")
        self.univPIC = QtWidgets.QLabel(self.cmdCHNG)
        self.univPIC.setGeometry(QtCore.QRect(10, 0, 101, 101))
        self.univPIC.setText("")
        self.univPIC.setPixmap(QtGui.QPixmap(":/Pictures/pictures/Universal-partner-icon(1).png"))
        self.univPIC.setObjectName("univPIC")
        self.winPIC = QtWidgets.QLabel(self.cmdCHNG)
        self.winPIC.setGeometry(QtCore.QRect(10, 100, 101, 101))
        self.winPIC.setText("")
        self.winPIC.setPixmap(QtGui.QPixmap(":/Pictures/pictures/windows-8-png-icon-7(1).png"))
        self.winPIC.setObjectName("winPIC")
        self.linPIC = QtWidgets.QLabel(self.cmdCHNG)
        self.linPIC.setGeometry(QtCore.QRect(10, 200, 101, 101))
        self.linPIC.setText("")
        self.linPIC.setPixmap(QtGui.QPixmap(":/Pictures/pictures/linuxICON(1).png"))
        self.linPIC.setObjectName("linPIC")
        self.macPIC = QtWidgets.QLabel(self.cmdCHNG)
        self.macPIC.setGeometry(QtCore.QRect(10, 300, 101, 101))
        self.macPIC.setText("")
        self.macPIC.setPixmap(QtGui.QPixmap(":/Pictures/pictures/MacOSx.png"))
        self.macPIC.setObjectName("macPIC")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 831, 121))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.header_title = QtWidgets.QLabel(self.header)
        self.header_title.setGeometry(QtCore.QRect(0, 0, 311, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.header_title.setFont(font)
        self.header_title.setStyleSheet("color: #8B93B2;")
        self.header_title.setText("")
        self.header_title.setObjectName("header_title")
        self.descriptions = QtWidgets.QLabel(self.header)
        self.descriptions.setGeometry(QtCore.QRect(320, 0, 501, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.descriptions.setFont(font)
        self.descriptions.setStyleSheet("color: #8B93B2;")
        self.descriptions.setObjectName("descriptions")
        self.quit_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button_3.setGeometry(QtCore.QRect(740, 530, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quit_button_3.setFont(font)
        self.quit_button_3.setStyleSheet("background-color: #414E6E;color: #8B93B2;")
        self.quit_button_3.setObjectName("quit_button_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(300, 120, 541, 401))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Universal_Page = QtWidgets.QWidget()
        self.Universal_Page.setObjectName("Universal_Page")
        self.label_8 = QtWidgets.QLabel(self.Universal_Page)
        self.label_8.setGeometry(QtCore.QRect(10, 310, 511, 81))
        self.label_8.setStyleSheet("color: #8B93B2;")
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.Universal_Page)
        self.frame.setGeometry(QtCore.QRect(0, 20, 541, 291))
        self.frame.setStyleSheet("background-color: #2E344A;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.srchmedbuttonUNI = QtWidgets.QPushButton(self.frame)
        self.srchmedbuttonUNI.setGeometry(QtCore.QRect(290, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.srchmedbuttonUNI.setFont(font)
        self.srchmedbuttonUNI.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.srchmedbuttonUNI.setObjectName("srchmedbuttonUNI")
        self.rmvprosoftbuttonUNI = QtWidgets.QPushButton(self.frame)
        self.rmvprosoftbuttonUNI.setGeometry(QtCore.QRect(10, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvprosoftbuttonUNI.setFont(font)
        self.rmvprosoftbuttonUNI.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvprosoftbuttonUNI.setObjectName("rmvprosoftbuttonUNI")
        self.Updates_buttonUNI = QtWidgets.QPushButton(self.frame)
        self.Updates_buttonUNI.setEnabled(True)
        self.Updates_buttonUNI.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Updates_buttonUNI.setFont(font)
        self.Updates_buttonUNI.setAcceptDrops(False)
        self.Updates_buttonUNI.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.Updates_buttonUNI.setCheckable(False)
        self.Updates_buttonUNI.setDefault(False)
        self.Updates_buttonUNI.setObjectName("Updates_buttonUNI")
        self.stackedWidget.addWidget(self.Universal_Page)
        self.Windows_Page = QtWidgets.QWidget()
        self.Windows_Page.setObjectName("Windows_Page")
        self.winTAB = QtWidgets.QTabWidget(self.Windows_Page)
        self.winTAB.setGeometry(QtCore.QRect(-10, 0, 561, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.winTAB.setFont(font)
        self.winTAB.setAutoFillBackground(False)
        self.winTAB.setStyleSheet("background-color: #2E344A;")
        self.winTAB.setObjectName("winTAB")
        self.windows_mainCOM = QtWidgets.QWidget()
        self.windows_mainCOM.setAutoFillBackground(False)
        self.windows_mainCOM.setObjectName("windows_mainCOM")
        self.srchmedbutton_2 = QtWidgets.QPushButton(self.windows_mainCOM)
        self.srchmedbutton_2.setGeometry(QtCore.QRect(300, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.srchmedbutton_2.setFont(font)
        self.srchmedbutton_2.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.srchmedbutton_2.setObjectName("srchmedbutton_2")
        self.basicConfbutton_2 = QtWidgets.QPushButton(self.windows_mainCOM)
        self.basicConfbutton_2.setGeometry(QtCore.QRect(300, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.basicConfbutton_2.setFont(font)
        self.basicConfbutton_2.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.basicConfbutton_2.setObjectName("basicConfbutton_2")
        self.rmvprosoftbutton_2 = QtWidgets.QPushButton(self.windows_mainCOM)
        self.rmvprosoftbutton_2.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvprosoftbutton_2.setFont(font)
        self.rmvprosoftbutton_2.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvprosoftbutton_2.setObjectName("rmvprosoftbutton_2")
        self.fwlbutton_2 = QtWidgets.QPushButton(self.windows_mainCOM)
        self.fwlbutton_2.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwlbutton_2.setFont(font)
        self.fwlbutton_2.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.fwlbutton_2.setObjectName("fwlbutton_2")
        self.label_13 = QtWidgets.QLabel(self.windows_mainCOM)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 451, 51))
        self.label_13.setStyleSheet("color: #8B93B2;")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.winTAB.addTab(self.windows_mainCOM, "")
        self.windows_usrgruCOM = QtWidgets.QWidget()
        self.windows_usrgruCOM.setObjectName("windows_usrgruCOM")
        self.lsmemgru_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.lsmemgru_3.setGeometry(QtCore.QRect(20, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsmemgru_3.setFont(font)
        self.lsmemgru_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lsmemgru_3.setObjectName("lsmemgru_3")
        self.chngusrpas_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.chngusrpas_3.setGeometry(QtCore.QRect(20, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chngusrpas_3.setFont(font)
        self.chngusrpas_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.chngusrpas_3.setObjectName("chngusrpas_3")
        self.rmvusrfrosys_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.rmvusrfrosys_3.setGeometry(QtCore.QRect(300, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrosys_3.setFont(font)
        self.rmvusrfrosys_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvusrfrosys_3.setObjectName("rmvusrfrosys_3")
        self.adusrtosys_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.adusrtosys_3.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtosys_3.setFont(font)
        self.adusrtosys_3.setAcceptDrops(False)
        self.adusrtosys_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adusrtosys_3.setObjectName("adusrtosys_3")
        self.rmvusrfrogru_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.rmvusrfrogru_3.setGeometry(QtCore.QRect(300, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrogru_3.setFont(font)
        self.rmvusrfrogru_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvusrfrogru_3.setObjectName("rmvusrfrogru_3")
        self.adgrutosys_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.adgrutosys_3.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adgrutosys_3.setFont(font)
        self.adgrutosys_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adgrutosys_3.setObjectName("adgrutosys_3")
        self.lslocausr_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.lslocausr_3.setGeometry(QtCore.QRect(20, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocausr_3.setFont(font)
        self.lslocausr_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lslocausr_3.setObjectName("lslocausr_3")
        self.rmvgrufrosys_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.rmvgrufrosys_3.setGeometry(QtCore.QRect(300, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvgrufrosys_3.setFont(font)
        self.rmvgrufrosys_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvgrufrosys_3.setObjectName("rmvgrufrosys_3")
        self.lslocagru_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.lslocagru_3.setGeometry(QtCore.QRect(300, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocagru_3.setFont(font)
        self.lslocagru_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lslocagru_3.setObjectName("lslocagru_3")
        self.lsgruusrin_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.lsgruusrin_3.setGeometry(QtCore.QRect(300, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsgruusrin_3.setFont(font)
        self.lsgruusrin_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lsgruusrin_3.setObjectName("lsgruusrin_3")
        self.adusrtogru_3 = QtWidgets.QPushButton(self.windows_usrgruCOM)
        self.adusrtogru_3.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtogru_3.setFont(font)
        self.adusrtogru_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adusrtogru_3.setObjectName("adusrtogru_3")
        self.label_14 = QtWidgets.QLabel(self.windows_usrgruCOM)
        self.label_14.setGeometry(QtCore.QRect(10, 320, 471, 51))
        self.label_14.setStyleSheet("color: #8B93B2;")
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.winTAB.addTab(self.windows_usrgruCOM, "")
        self.stackedWidget.addWidget(self.Windows_Page)
        self.Linux_Page = QtWidgets.QWidget()
        self.Linux_Page.setObjectName("Linux_Page")
        self.linTAB = QtWidgets.QTabWidget(self.Linux_Page)
        self.linTAB.setGeometry(QtCore.QRect(-10, 0, 561, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linTAB.setFont(font)
        self.linTAB.setStyleSheet("background-color: #2E344A;")
        self.linTAB.setObjectName("linTAB")
        self.linux_mainCOM = QtWidgets.QWidget()
        self.linux_mainCOM.setObjectName("linux_mainCOM")
        self.auditbutton_3 = QtWidgets.QPushButton(self.linux_mainCOM)
        self.auditbutton_3.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auditbutton_3.setFont(font)
        self.auditbutton_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.auditbutton_3.setObjectName("auditbutton_3")
        self.srchmedbutton_3 = QtWidgets.QPushButton(self.linux_mainCOM)
        self.srchmedbutton_3.setGeometry(QtCore.QRect(300, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.srchmedbutton_3.setFont(font)
        self.srchmedbutton_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.srchmedbutton_3.setObjectName("srchmedbutton_3")
        self.basicConfbutton_3 = QtWidgets.QPushButton(self.linux_mainCOM)
        self.basicConfbutton_3.setGeometry(QtCore.QRect(300, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.basicConfbutton_3.setFont(font)
        self.basicConfbutton_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.basicConfbutton_3.setObjectName("basicConfbutton_3")
        self.rmvprosoftbutton_3 = QtWidgets.QPushButton(self.linux_mainCOM)
        self.rmvprosoftbutton_3.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvprosoftbutton_3.setFont(font)
        self.rmvprosoftbutton_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvprosoftbutton_3.setObjectName("rmvprosoftbutton_3")
        self.malrembutton_3 = QtWidgets.QPushButton(self.linux_mainCOM)
        self.malrembutton_3.setGeometry(QtCore.QRect(300, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.malrembutton_3.setFont(font)
        self.malrembutton_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.malrembutton_3.setObjectName("malrembutton_3")
        self.fwlbutton_3 = QtWidgets.QPushButton(self.linux_mainCOM)
        self.fwlbutton_3.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwlbutton_3.setFont(font)
        self.fwlbutton_3.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.fwlbutton_3.setObjectName("fwlbutton_3")
        self.label_15 = QtWidgets.QLabel(self.linux_mainCOM)
        self.label_15.setGeometry(QtCore.QRect(10, 320, 511, 51))
        self.label_15.setStyleSheet("color: #8B93B2;")
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.linTAB.addTab(self.linux_mainCOM, "")
        self.linux_usrgruCOM = QtWidgets.QWidget()
        self.linux_usrgruCOM.setObjectName("linux_usrgruCOM")
        self.lsmemgru_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.lsmemgru_4.setGeometry(QtCore.QRect(20, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsmemgru_4.setFont(font)
        self.lsmemgru_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lsmemgru_4.setObjectName("lsmemgru_4")
        self.chngusrpas_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.chngusrpas_4.setGeometry(QtCore.QRect(20, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chngusrpas_4.setFont(font)
        self.chngusrpas_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.chngusrpas_4.setObjectName("chngusrpas_4")
        self.rmvusrfrosys_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.rmvusrfrosys_4.setGeometry(QtCore.QRect(300, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrosys_4.setFont(font)
        self.rmvusrfrosys_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvusrfrosys_4.setObjectName("rmvusrfrosys_4")
        self.adusrtosys_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.adusrtosys_4.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtosys_4.setFont(font)
        self.adusrtosys_4.setAcceptDrops(False)
        self.adusrtosys_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adusrtosys_4.setObjectName("adusrtosys_4")
        self.rmvusrfrogru_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.rmvusrfrogru_4.setGeometry(QtCore.QRect(300, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrogru_4.setFont(font)
        self.rmvusrfrogru_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvusrfrogru_4.setObjectName("rmvusrfrogru_4")
        self.adgrutosys_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.adgrutosys_4.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adgrutosys_4.setFont(font)
        self.adgrutosys_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adgrutosys_4.setObjectName("adgrutosys_4")
        self.lslocausr_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.lslocausr_4.setGeometry(QtCore.QRect(20, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocausr_4.setFont(font)
        self.lslocausr_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lslocausr_4.setObjectName("lslocausr_4")
        self.rmvgrufrosys_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.rmvgrufrosys_4.setGeometry(QtCore.QRect(300, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvgrufrosys_4.setFont(font)
        self.rmvgrufrosys_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvgrufrosys_4.setObjectName("rmvgrufrosys_4")
        self.lslocagru_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.lslocagru_4.setGeometry(QtCore.QRect(300, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocagru_4.setFont(font)
        self.lslocagru_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lslocagru_4.setObjectName("lslocagru_4")
        self.lsgruusrin_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.lsgruusrin_4.setGeometry(QtCore.QRect(300, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsgruusrin_4.setFont(font)
        self.lsgruusrin_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lsgruusrin_4.setObjectName("lsgruusrin_4")
        self.adusrtogru_4 = QtWidgets.QPushButton(self.linux_usrgruCOM)
        self.adusrtogru_4.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtogru_4.setFont(font)
        self.adusrtogru_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adusrtogru_4.setObjectName("adusrtogru_4")
        self.label_16 = QtWidgets.QLabel(self.linux_usrgruCOM)
        self.label_16.setGeometry(QtCore.QRect(10, 320, 511, 51))
        self.label_16.setStyleSheet("color: #8B93B2;")
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.linTAB.addTab(self.linux_usrgruCOM, "")
        self.stackedWidget.addWidget(self.Linux_Page)
        self.MacOS_Page = QtWidgets.QWidget()
        self.MacOS_Page.setObjectName("MacOS_Page")
        self.macTAB = QtWidgets.QTabWidget(self.MacOS_Page)
        self.macTAB.setGeometry(QtCore.QRect(-10, 0, 561, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.macTAB.setFont(font)
        self.macTAB.setStyleSheet("background-color: #2E344A;")
        self.macTAB.setObjectName("macTAB")
        self.mac_mainCOM = QtWidgets.QWidget()
        self.mac_mainCOM.setAutoFillBackground(False)
        self.mac_mainCOM.setObjectName("mac_mainCOM")
        self.auditbutton_4 = QtWidgets.QPushButton(self.mac_mainCOM)
        self.auditbutton_4.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auditbutton_4.setFont(font)
        self.auditbutton_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.auditbutton_4.setObjectName("auditbutton_4")
        self.srchmedbutton_4 = QtWidgets.QPushButton(self.mac_mainCOM)
        self.srchmedbutton_4.setGeometry(QtCore.QRect(300, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.srchmedbutton_4.setFont(font)
        self.srchmedbutton_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.srchmedbutton_4.setObjectName("srchmedbutton_4")
        self.basicConfbutton_4 = QtWidgets.QPushButton(self.mac_mainCOM)
        self.basicConfbutton_4.setGeometry(QtCore.QRect(300, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.basicConfbutton_4.setFont(font)
        self.basicConfbutton_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.basicConfbutton_4.setObjectName("basicConfbutton_4")
        self.rmvprosoftbutton_4 = QtWidgets.QPushButton(self.mac_mainCOM)
        self.rmvprosoftbutton_4.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvprosoftbutton_4.setFont(font)
        self.rmvprosoftbutton_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvprosoftbutton_4.setObjectName("rmvprosoftbutton_4")
        self.malrembutton_4 = QtWidgets.QPushButton(self.mac_mainCOM)
        self.malrembutton_4.setGeometry(QtCore.QRect(300, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.malrembutton_4.setFont(font)
        self.malrembutton_4.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.malrembutton_4.setObjectName("malrembutton_4")
        self.label_17 = QtWidgets.QLabel(self.mac_mainCOM)
        self.label_17.setGeometry(QtCore.QRect(10, 320, 421, 51))
        self.label_17.setStyleSheet("color: #8B93B2;")
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.macTAB.addTab(self.mac_mainCOM, "")
        self.mac_usrgruCOM = QtWidgets.QWidget()
        self.mac_usrgruCOM.setObjectName("mac_usrgruCOM")
        self.lsmemgru_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.lsmemgru_5.setGeometry(QtCore.QRect(20, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsmemgru_5.setFont(font)
        self.lsmemgru_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lsmemgru_5.setObjectName("lsmemgru_5")
        self.chngusrpas_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.chngusrpas_5.setGeometry(QtCore.QRect(20, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chngusrpas_5.setFont(font)
        self.chngusrpas_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.chngusrpas_5.setObjectName("chngusrpas_5")
        self.rmvusrfrosys_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.rmvusrfrosys_5.setGeometry(QtCore.QRect(300, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrosys_5.setFont(font)
        self.rmvusrfrosys_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvusrfrosys_5.setObjectName("rmvusrfrosys_5")
        self.adusrtosys_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.adusrtosys_5.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtosys_5.setFont(font)
        self.adusrtosys_5.setAcceptDrops(False)
        self.adusrtosys_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adusrtosys_5.setObjectName("adusrtosys_5")
        self.rmvusrfrogru_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.rmvusrfrogru_5.setGeometry(QtCore.QRect(300, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvusrfrogru_5.setFont(font)
        self.rmvusrfrogru_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvusrfrogru_5.setObjectName("rmvusrfrogru_5")
        self.adgrutosys_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.adgrutosys_5.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adgrutosys_5.setFont(font)
        self.adgrutosys_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adgrutosys_5.setObjectName("adgrutosys_5")
        self.lslocausr_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.lslocausr_5.setGeometry(QtCore.QRect(20, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocausr_5.setFont(font)
        self.lslocausr_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lslocausr_5.setObjectName("lslocausr_5")
        self.rmvgrufrosys_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.rmvgrufrosys_5.setGeometry(QtCore.QRect(300, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rmvgrufrosys_5.setFont(font)
        self.rmvgrufrosys_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.rmvgrufrosys_5.setObjectName("rmvgrufrosys_5")
        self.lslocagru_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.lslocagru_5.setGeometry(QtCore.QRect(300, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lslocagru_5.setFont(font)
        self.lslocagru_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lslocagru_5.setObjectName("lslocagru_5")
        self.lsgruusrin_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.lsgruusrin_5.setGeometry(QtCore.QRect(300, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsgruusrin_5.setFont(font)
        self.lsgruusrin_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.lsgruusrin_5.setObjectName("lsgruusrin_5")
        self.adusrtogru_5 = QtWidgets.QPushButton(self.mac_usrgruCOM)
        self.adusrtogru_5.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adusrtogru_5.setFont(font)
        self.adusrtogru_5.setStyleSheet("background-color: #414E6E;color: #CCD2E6;")
        self.adusrtogru_5.setObjectName("adusrtogru_5")
        self.label_18 = QtWidgets.QLabel(self.mac_usrgruCOM)
        self.label_18.setGeometry(QtCore.QRect(10, 320, 421, 51))
        self.label_18.setStyleSheet("color: #8B93B2;")
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.macTAB.addTab(self.mac_usrgruCOM, "")
        self.stackedWidget.addWidget(self.MacOS_Page)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 540, 291, 41))
        self.label_7.setStyleSheet("color: #8B93B2;")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("color: #8B93B2; background-color: #2E344A;")
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("")
        self.menuHelp.setObjectName("menuHelp")
        self.menuChange_Configurations = QtWidgets.QMenu(self.menubar)
        self.menuChange_Configurations.setObjectName("menuChange_Configurations")
        self.menuLighting_Mode = QtWidgets.QMenu(self.menubar)
        self.menuLighting_Mode.setObjectName("menuLighting_Mode")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_Creator = QtWidgets.QAction(MainWindow)
        self.actionAbout_Creator.setObjectName("actionAbout_Creator")
        self.actionHow_To_Use_Program = QtWidgets.QAction(MainWindow)
        self.actionHow_To_Use_Program.setObjectName("actionHow_To_Use_Program")
        self.actionLight_Mode = QtWidgets.QAction(MainWindow)
        self.actionLight_Mode.setObjectName("actionLight_Mode")
        self.actionDark_Mode = QtWidgets.QAction(MainWindow)
        self.actionDark_Mode.setObjectName("actionDark_Mode")
        self.menuHelp.addAction(self.actionAbout_Creator)
        self.menuHelp.addAction(self.actionHow_To_Use_Program)
        self.menuLighting_Mode.addAction(self.actionLight_Mode)
        self.menuLighting_Mode.addAction(self.actionDark_Mode)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuChange_Configurations.menuAction())
        self.menubar.addAction(self.menuLighting_Mode.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.winTAB.setCurrentIndex(0)
        self.linTAB.setCurrentIndex(0)
        self.macTAB.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.uniCom, self.winCom)
        MainWindow.setTabOrder(self.winCom, self.linCom)
        MainWindow.setTabOrder(self.linCom, self.macCom)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Apple CIDR Script Runner"))
        self.uniCom.setText(_translate("MainWindow", "Universal Commands"))
        self.winCom.setText(_translate("MainWindow", "Windows Commands"))
        self.linCom.setText(_translate("MainWindow", "Linux Commands"))
        self.macCom.setText(_translate("MainWindow", "MacOS Only Commands"))
        self.descriptions.setText(_translate("MainWindow", "<html><head/><body><p>Description: These commands will work on most Operating Systems </p><p>(Windows, MacOS X, and Linux (Debian, Ubuntu, certain Arch distros))</p></body></html>"))
        self.quit_button_3.setText(_translate("MainWindow", "Quit"))
        self.quit_button_3.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>All Commands here will work across all Operating Systems</p><p>It is recommended that you use the commands that goes with the system that you are using.</p><p>Ex: If you are using a Windows PC, use the Windows Commands</p></body></html>"))
        self.srchmedbuttonUNI.setText(_translate("MainWindow", "Search For Prohibited Media"))
        self.rmvprosoftbuttonUNI.setText(_translate("MainWindow", "Remove Prohibited Software"))
        self.Updates_buttonUNI.setText(_translate("MainWindow", "Update System"))
        self.srchmedbutton_2.setText(_translate("MainWindow", "Search For Prohibited Media"))
        self.basicConfbutton_2.setText(_translate("MainWindow", "Basic Configurations"))
        self.rmvprosoftbutton_2.setText(_translate("MainWindow", "Remove Prohibited Software*"))
        self.fwlbutton_2.setText(_translate("MainWindow", "Windows Firewall Settings"))
        self.label_13.setText(_translate("MainWindow", "All Commands here will work on Windows 10"))
        self.winTAB.setTabText(self.winTAB.indexOf(self.windows_mainCOM), _translate("MainWindow", "Main Commands"))
        self.lsmemgru_3.setText(_translate("MainWindow", "List Members of Group"))
        self.chngusrpas_3.setText(_translate("MainWindow", "Change all Users Passwords at Once"))
        self.rmvusrfrosys_3.setText(_translate("MainWindow", "Remove User From System"))
        self.adusrtosys_3.setText(_translate("MainWindow", "Add User to System"))
        self.rmvusrfrogru_3.setText(_translate("MainWindow", "Remove User from Group"))
        self.adgrutosys_3.setText(_translate("MainWindow", "Add Group to System"))
        self.lslocausr_3.setText(_translate("MainWindow", "List Local Users"))
        self.rmvgrufrosys_3.setText(_translate("MainWindow", "Remove Group from System"))
        self.lslocagru_3.setText(_translate("MainWindow", "List Local Groups"))
        self.lsgruusrin_3.setText(_translate("MainWindow", "List Groups an User is in"))
        self.adusrtogru_3.setText(_translate("MainWindow", "Add User to Group"))
        self.label_14.setText(_translate("MainWindow", "All Commands here will work on Windows 10"))
        self.winTAB.setTabText(self.winTAB.indexOf(self.windows_usrgruCOM), _translate("MainWindow", "User / Group Settings"))
        self.auditbutton_3.setText(_translate("MainWindow", "Audit System"))
        self.srchmedbutton_3.setText(_translate("MainWindow", "Search For Prohibited Media"))
        self.basicConfbutton_3.setText(_translate("MainWindow", "Basic Configurations"))
        self.rmvprosoftbutton_3.setText(_translate("MainWindow", "Remove Prohibited Software"))
        self.malrembutton_3.setText(_translate("MainWindow", "Malware Removal"))
        self.fwlbutton_3.setText(_translate("MainWindow", "Firewall Settings"))
        self.label_15.setText(_translate("MainWindow", "All Commands here will work on Debian/Ubuntu/Manjaro Linux distributions"))
        self.linTAB.setTabText(self.linTAB.indexOf(self.linux_mainCOM), _translate("MainWindow", "Main Commands"))
        self.lsmemgru_4.setText(_translate("MainWindow", "List Members of Group"))
        self.chngusrpas_4.setText(_translate("MainWindow", "Change all Users Passwords at Once"))
        self.rmvusrfrosys_4.setText(_translate("MainWindow", "Remove User From System"))
        self.adusrtosys_4.setText(_translate("MainWindow", "Add User to System"))
        self.rmvusrfrogru_4.setText(_translate("MainWindow", "Remove User from Group"))
        self.adgrutosys_4.setText(_translate("MainWindow", "Add Group to System"))
        self.lslocausr_4.setText(_translate("MainWindow", "List Local Users"))
        self.rmvgrufrosys_4.setText(_translate("MainWindow", "Remove Group from System"))
        self.lslocagru_4.setText(_translate("MainWindow", "List Local Groups"))
        self.lsgruusrin_4.setText(_translate("MainWindow", "List Groups an User is in"))
        self.adusrtogru_4.setText(_translate("MainWindow", "Add User to Group"))
        self.label_16.setText(_translate("MainWindow", "All Commands here will work on Debian/Ubuntu/Manjaro Linux distrobutions"))
        self.linTAB.setTabText(self.linTAB.indexOf(self.linux_usrgruCOM), _translate("MainWindow", "User / Group Settings"))
        self.auditbutton_4.setText(_translate("MainWindow", "Audit System*"))
        self.srchmedbutton_4.setText(_translate("MainWindow", "Search For Prohibited Media"))
        self.basicConfbutton_4.setText(_translate("MainWindow", "Basic Configurations"))
        self.rmvprosoftbutton_4.setText(_translate("MainWindow", "Remove Prohibited Software"))
        self.malrembutton_4.setText(_translate("MainWindow", "Malware Removal"))
        self.label_17.setText(_translate("MainWindow", "All Commands here will work on MacOS X"))
        self.macTAB.setTabText(self.macTAB.indexOf(self.mac_mainCOM), _translate("MainWindow", "Main Commands"))
        self.lsmemgru_5.setText(_translate("MainWindow", "List Members of Group"))
        self.chngusrpas_5.setText(_translate("MainWindow", "Change all Users Passwords at Once"))
        self.rmvusrfrosys_5.setText(_translate("MainWindow", "Remove User From System"))
        self.adusrtosys_5.setText(_translate("MainWindow", "Add User to System"))
        self.rmvusrfrogru_5.setText(_translate("MainWindow", "Remove User from Group"))
        self.adgrutosys_5.setText(_translate("MainWindow", "Add Group to System"))
        self.lslocausr_5.setText(_translate("MainWindow", "List Local Users"))
        self.rmvgrufrosys_5.setText(_translate("MainWindow", "Remove Group from System"))
        self.lslocagru_5.setText(_translate("MainWindow", "List Local Groups"))
        self.lsgruusrin_5.setText(_translate("MainWindow", "List Groups an User is in"))
        self.adusrtogru_5.setText(_translate("MainWindow", "Add User to Group"))
        self.label_18.setText(_translate("MainWindow", "All Commands here will work on MacOS X"))
        self.macTAB.setTabText(self.macTAB.indexOf(self.mac_usrgruCOM), _translate("MainWindow", "User / Group Settings"))
        self.label_7.setText(_translate("MainWindow", "<Running Commands Progress Bar will be here>"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuChange_Configurations.setTitle(_translate("MainWindow", "Change Configurations"))
        self.menuLighting_Mode.setTitle(_translate("MainWindow", "Light/Dark Mode Settings"))
        self.actionAbout_Creator.setText(_translate("MainWindow", "About Creator"))
        self.actionHow_To_Use_Program.setText(_translate("MainWindow", "How To Use Program"))
        self.actionLight_Mode.setText(_translate("MainWindow", "Light Mode"))
        self.actionDark_Mode.setText(_translate("MainWindow", "Dark Mode"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
