# This is the basic workflow to help you get started with Actions

name: Compilation

# Controls when the action will run
on:
  # Triggers the workflow on push request events but only for the dev branch
  push:
    branches: [dev]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Linux_Build"
  Linux_Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Changing Test-Scripts to Executables
        run: |
          sudo chmod +x ./builds/tests/compile_test.sh
          sudo chmod +x ./builds/tests/after_successCONVERT.sh

      - name: Installing Dependencies
        run: |
          pip3 install -r ./GUIs/ScriptRunnerPyQt5_GUI/requirements.txt
          /home/runner/.local/bin/pyinstaller --version

      - name: Build Executables
        run:
          sudo sh ./builds/tests/compile_test.sh linux

      - name: Upload to Github
        run:
          sudo sh ./builds/tests/after_successCONVERT.sh

